AddonId: PS5ish_676e10ec-adfe-48d8-a1bd-4d5771b5a2ca
Packages:
  - Version: 4.0.0
    RequiredApiVersion: 2.0.0
    ReleaseDate: 2021-10-06
    PackageUrl: https://github.com/davidkgriggs/PS5ish/releases/download/v4.0.0/PS5ish_676e10ec-adfe-48d8-a1bd-4d5771b5a2ca_4_0_0.pthm
    Changelog:
      - Rebuilt for Playnite v9
